apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-showcase
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: fluxcd-2022
  url: https://github.com/biela000/fluxcd-showcase
